# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

topology:
    Server:
        'admin-server':
            AdministrationPortEnabled: true
            AdministrationPort: 7099
            MaxMessageSize: 78787878
            NetworkAccessPoint:
                T3Channel1:
                    ListenAddress: '@@ENV:DOMAIN_UID@@-admin-server'
                    PublicPort: 40012
                T3Channel2:
                    ListenAddress: '@@ENV:DOMAIN_UID@@-admin-server'
                    PublicPort: 40013
                T3Channel3:
                    PublicAddress: 'mycustompublicaddress'
                    ListenPort: 40014
        standalone1:
            MaxMessageSize: 1111111
        standalone2:
            MaxMessageSize: 2222222

resources:
    JDBCSystemResource:
        mysqlDS:
            JdbcResource:
                JDBCDriverParams:
                    URL: 'jdbc:mysql://@@ENV:DOMAIN_UID@@-mysql:3306/mysql'
                    Properties:
                        user:
                            Value: '@@SECRET:@@ENV:DOMAIN_UID@@-mysql-secret:root-user@@'
