apiVersion: v1
entries:
  weblogic-operator:
  - apiVersion: v1
    appVersion: 3.1.2
    created: "2021-01-22T12:54:51.467995-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 2d8b77038ba870cc66ddd45e07a593a5ac3159c8b9531b5309688028b5268a5f
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.2.tgz
    version: 3.1.2
  - apiVersion: v1
    appVersion: 3.1.1
    created: "2021-01-22T12:54:51.467146-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: d0e371926643a25769de441cc336198e6a7d53b0f33b66d956726612046f89b1
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.1.tgz
    version: 3.1.1
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2021-01-22T12:54:51.465763-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: acf600d0951dc3d8a0b05b35f3b9b1e62d827ef483fa863b0e37054ebb61f853
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.464524-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 5d3a79a55132c33afd5d2d30e398c3cc508d77c9352129f2e8e127db5f1dcf19
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.4.tgz
    version: 3.0.4
  - apiVersion: v1
    created: "2021-01-22T12:54:51.463192-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: c6aeefca88eaa0d431dba66ee5705391c92468f26b27c5af92815ec3c3000406
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.3.tgz
    version: 3.0.3
  - apiVersion: v1
    created: "2021-01-22T12:54:51.462065-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 84b5989fe8f2392d2b3b0f721bdab1562566d7d885324beafd9fc9e658b13cd3
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v1
    created: "2021-01-22T12:54:51.461286-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: e7654ad3f2168f54b3a4b133bf8a86ea12bc474e5ee1d3ab14e1cf53012e9772
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    created: "2021-01-22T12:54:51.460493-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 5c7c0d3ae797e98592b6fd2191b104f515d6649d0060af0a3ffef215d4c69864
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.459726-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 5f4cd8f4f3282b52b5e90a1169f26986e8272671845053606ade9c855fb04151
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0-rc1.tgz
    version: 3.0.0-rc1
  - apiVersion: v1
    created: "2021-01-22T12:54:51.458901-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: d441888a8deae1b1339e7585e3b437dfd2533303e46e842d7378e16db665e234
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.458077-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: fe41421b7dc45dc8a3b2888d3a626a37f5d3c8e1fa292fb6699deedc5e1db33d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.457046-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: b36bd32083f67453a62d089a2c09ce38e6655d88ac8a7b38691230c55c40e672
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.455971-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: a3eafe4c2c6ff49384e56421201e59a3737d651af8d5b605b87a19eb1f6f1dc3
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v1
    created: "2021-01-22T12:54:51.451996-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: cbc6caaa6eb28e3c7e906ede14b2ae511a0b35fc12a8e3ab629155b09993e8b2
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.451059-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 23d5a1c554fa8211cc1e86b7ade09460917cb2069e68fb4bfdddafc8db44fdcd
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v1
    created: "2021-01-22T12:54:51.449927-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: bba303686cb55d84fe8c0d693a2436e7e686b028085b56e012f6381699a3911f
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v1
    created: "2021-01-22T12:54:51.449076-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 391e23c0969ada5f0cd2a088ddc6f11f237f57521801ed3925db2149a8437a0d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.1.tgz
    version: "2.1"
  - apiVersion: v1
    created: "2021-01-22T12:54:51.448216-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 298acda78ab73db6b7ba6f2752311bfa40c65874e03fb196b70976192211c1a5
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.0.1.tgz
    version: 2.0.1
generated: "2021-01-22T12:54:51.446133-05:00"
