apiVersion: v1
entries:
  weblogic-operator:
  - apiVersion: v1
    created: "2020-11-03T13:26:35.139696-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: c6aeefca88eaa0d431dba66ee5705391c92468f26b27c5af92815ec3c3000406
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.3.tgz
    version: 3.0.3
  - apiVersion: v1
    created: "2020-11-03T13:26:35.136316-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 84b5989fe8f2392d2b3b0f721bdab1562566d7d885324beafd9fc9e658b13cd3
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v1
    created: "2020-11-03T13:26:35.134574-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: e7654ad3f2168f54b3a4b133bf8a86ea12bc474e5ee1d3ab14e1cf53012e9772
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    created: "2020-11-03T13:26:35.132285-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 303288a48a6075d52538bb4e17dd46f8b1431158ee81bc878d9f1f264d30192e
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.130703-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 5f4cd8f4f3282b52b5e90a1169f26986e8272671845053606ade9c855fb04151
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0-rc1.tgz
    version: 3.0.0-rc1
  - apiVersion: v1
    created: "2020-11-03T13:26:35.129082-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: d441888a8deae1b1339e7585e3b437dfd2533303e46e842d7378e16db665e234
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.127537-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: fe41421b7dc45dc8a3b2888d3a626a37f5d3c8e1fa292fb6699deedc5e1db33d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.121802-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: b36bd32083f67453a62d089a2c09ce38e6655d88ac8a7b38691230c55c40e672
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.100833-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: a3eafe4c2c6ff49384e56421201e59a3737d651af8d5b605b87a19eb1f6f1dc3
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v1
    created: "2020-11-03T13:26:35.093279-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: cbc6caaa6eb28e3c7e906ede14b2ae511a0b35fc12a8e3ab629155b09993e8b2
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.090449-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 23d5a1c554fa8211cc1e86b7ade09460917cb2069e68fb4bfdddafc8db44fdcd
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v1
    created: "2020-11-03T13:26:35.08903-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: bba303686cb55d84fe8c0d693a2436e7e686b028085b56e012f6381699a3911f
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v1
    created: "2020-11-03T13:26:35.087766-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 391e23c0969ada5f0cd2a088ddc6f11f237f57521801ed3925db2149a8437a0d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.1.tgz
    version: "2.1"
  - apiVersion: v1
    created: "2020-11-03T13:26:35.086417-05:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 298acda78ab73db6b7ba6f2752311bfa40c65874e03fb196b70976192211c1a5
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.0.1.tgz
    version: 2.0.1
generated: "2020-11-03T13:26:35.085005-05:00"
