apiVersion: v1
entries:
  weblogic-operator:
  - created: 2019-11-18T22:46:14.921203791Z
    description: Helm chart for configuring the WebLogic operator.
    digest: cc6d2ca9a48b3d82638857f78905ff0ecee7c401cda4f7528d58649e9997c4f5
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.4.0.tgz
    version: 2.4.0
  - created: 2019-11-18T22:46:14.919592211Z
    description: Helm chart for configuring the WebLogic operator.
    digest: e4054e1204c30c9a4c551dbed0bd71fd909734ae0976424fb19686961815f5f4
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.1.tgz
    version: 2.3.1
  - created: 2019-11-18T22:46:14.918695Z
    description: Helm chart for configuring the WebLogic operator.
    digest: 862b4b0e6fe474b18aea8f9bad6596b7ff744853daa4ccbf8f1aa0ea36e777b0
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.0.tgz
    version: 2.3.0
  - created: 2019-11-18T22:46:14.918080007Z
    description: Helm chart for configuring the WebLogic operator.
    digest: 23d5a1c554fa8211cc1e86b7ade09460917cb2069e68fb4bfdddafc8db44fdcd
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.1.tgz
    version: 2.2.1
  - created: 2019-11-18T22:46:14.917400933Z
    description: Helm chart for configuring the WebLogic operator.
    digest: bba303686cb55d84fe8c0d693a2436e7e686b028085b56e012f6381699a3911f
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.0.tgz
    version: 2.2.0
  - created: 2019-11-18T22:46:14.916625521Z
    description: Helm chart for configuring the WebLogic operator.
    digest: 391e23c0969ada5f0cd2a088ddc6f11f237f57521801ed3925db2149a8437a0d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.1.tgz
    version: "2.1"
  - created: 2019-11-18T22:46:14.915906977Z
    description: Helm chart for configuring the WebLogic operator.
    digest: 298acda78ab73db6b7ba6f2752311bfa40c65874e03fb196b70976192211c1a5
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.0.1.tgz
    version: 2.0.1
generated: 2019-11-18T22:46:14.914736614Z
