apiVersion: v1
entries:
  weblogic-operator:
  - apiVersion: v1
    appVersion: 3.3.2
    created: "2021-08-31T17:21:51.947853-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: d2a865573129cb14122956a1a787c058859947e5687f651ea3f2eeff2ac7329e
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.3.2.tgz
    version: 3.3.2
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2021-08-31T17:21:51.946161-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 39c84df7ee4ff70bea1752fe0ddfc98da14d9cbd3521b701310f0fbb15aaf938
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.3.1.tgz
    version: 3.3.1
  - apiVersion: v1
    appVersion: 3.3.0
    created: "2021-08-31T17:21:51.905906-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: efd0ece5ebe1a7b4d826b44af71bbdf08f2c1b3573072a9d5725ca1b3ee18841
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.3.0.tgz
    version: 3.3.0
  - apiVersion: v1
    appVersion: 3.2.5
    created: "2021-08-31T17:21:51.903802-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: fc90fc05e628fd7f019e4d4a7cfa5bcc3d728979d4baa729e667a95c9767aeaa
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.5.tgz
    version: 3.2.5
  - apiVersion: v1
    appVersion: 3.2.4
    created: "2021-08-31T17:21:51.901979-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: b6fe80badb65a88c59d0f6f069e7838906451d19baa24ad6744b8a4ce3d51614
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.4.tgz
    version: 3.2.4
  - apiVersion: v1
    appVersion: 3.2.3
    created: "2021-08-31T17:21:51.899559-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 7a51397c11fdca27a23150abd7816c330009aca791e6013f959c69226b7bd89b
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.3.tgz
    version: 3.2.3
  - apiVersion: v1
    appVersion: 3.2.2
    created: "2021-08-31T17:21:51.89632-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: a4101539f527fd8ac80cfaa5314e8ba10a28f5bba462b75932a9bed1b83874bf
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.2.tgz
    version: 3.2.2
  - apiVersion: v1
    appVersion: 3.2.1
    created: "2021-08-31T17:21:51.85587-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 002da958caed9fe625e11b075a5c6df28be956854a0b41dae46f0108a70f9321
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.1.tgz
    version: 3.2.1
  - apiVersion: v1
    appVersion: 3.2.0
    created: "2021-08-31T17:21:51.85439-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: e1c9192b3590d10b8426b7e7bcae27213d9f2296ef4f2cf547e198fd2d89ab1b
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.2.0.tgz
    version: 3.2.0
  - apiVersion: v1
    appVersion: 3.1.4
    created: "2021-08-31T17:21:51.852838-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 9695fd3c29cd4f006f8e75ae0053683c9aa7213440525002f4f3d36eb8d86633
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.4.tgz
    version: 3.1.4
  - apiVersion: v1
    appVersion: 3.1.3
    created: "2021-08-31T17:21:51.850037-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: e306bd590dbe84400c6b5bb7a64325330e597223dff63792bb5811c9cfae10ac
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.3.tgz
    version: 3.1.3
  - apiVersion: v1
    appVersion: 3.1.2
    created: "2021-08-31T17:21:51.847763-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 2d8b77038ba870cc66ddd45e07a593a5ac3159c8b9531b5309688028b5268a5f
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.2.tgz
    version: 3.1.2
  - apiVersion: v1
    appVersion: 3.1.1
    created: "2021-08-31T17:21:51.845413-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: d839cb7bbce4421a59cd9c3df64b1df8649eeebcb6c6b7be34fec25ad00aa141
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.1.tgz
    version: 3.1.1
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2021-08-31T17:21:51.805321-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 9e105bec11bab249973370a4d5e653f9104cd9fbaaa0c2090fb173805fb3a692
    name: weblogic-operator
    type: application
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.803433-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 9dad4d85a6165dbfc57d0baadb5186a5c43c718a1a3ee2dbd6e886fe660cd65a
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.4.tgz
    version: 3.0.4
  - apiVersion: v1
    created: "2021-08-31T17:21:51.801798-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 83a0ac84a033ddd9939d4bc5884cc60b22225d7326c43ce8e54a6f403b453814
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.3.tgz
    version: 3.0.3
  - apiVersion: v1
    created: "2021-08-31T17:21:51.799946-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: fa3af5d21f858ff93cc7d58664a6eb0a920207af09e4c669a7ffb12e9e15b88d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v1
    created: "2021-08-31T17:21:51.797899-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: aa2b2afe75305bd69f6b07d61e64a37d3bfd249074c81f6a999cef6b4a217fd0
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    created: "2021-08-31T17:21:51.795915-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 6540a3a7c6a1c34fcf2ff66679947a1964a35e61232b2a8dea3da087a2d5411d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.75577-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 5f4cd8f4f3282b52b5e90a1169f26986e8272671845053606ade9c855fb04151
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-3.0.0-rc1.tgz
    version: 3.0.0-rc1
  - apiVersion: v1
    created: "2021-08-31T17:21:51.754344-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: e3596b2380b264a0a70ba438858ca9af102a79689bf2e21e237eb63ea2997d66
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.752629-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: fe41421b7dc45dc8a3b2888d3a626a37f5d3c8e1fa292fb6699deedc5e1db33d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.750913-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: b36bd32083f67453a62d089a2c09ce38e6655d88ac8a7b38691230c55c40e672
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.747905-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: a3eafe4c2c6ff49384e56421201e59a3737d651af8d5b605b87a19eb1f6f1dc3
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v1
    created: "2021-08-31T17:21:51.705265-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: cbc6caaa6eb28e3c7e906ede14b2ae511a0b35fc12a8e3ab629155b09993e8b2
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.703275-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 23d5a1c554fa8211cc1e86b7ade09460917cb2069e68fb4bfdddafc8db44fdcd
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v1
    created: "2021-08-31T17:21:51.701306-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: bba303686cb55d84fe8c0d693a2436e7e686b028085b56e012f6381699a3911f
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v1
    created: "2021-08-31T17:21:51.699583-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 391e23c0969ada5f0cd2a088ddc6f11f237f57521801ed3925db2149a8437a0d
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.1.tgz
    version: "2.1"
  - apiVersion: v1
    created: "2021-08-31T17:21:51.697643-04:00"
    description: Helm chart for configuring the WebLogic operator.
    digest: 298acda78ab73db6b7ba6f2752311bfa40c65874e03fb196b70976192211c1a5
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.0.1.tgz
    version: 2.0.1
generated: "2021-08-31T17:21:51.694682-04:00"
