# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: batch/v1
kind: Job
metadata:
  name: %DOMAIN_UID%-create-fmw-infra-sample-domain-job
  namespace: %NAMESPACE%
spec:
  template:
    metadata:
      labels:
        weblogic.resourceVersion: domain-v2
        weblogic.domainUID: %DOMAIN_UID%
        weblogic.domainName: %DOMAIN_NAME%
        app: %DOMAIN_UID%-create-fmw-infra-sample-domain-job
    spec:
      restartPolicy: Never
      containers:
        - name: create-fmw-infra-sample-domain-job
          image: %WEBLOGIC_IMAGE%
          imagePullPolicy: %WEBLOGIC_IMAGE_PULL_POLICY%
          ports:
            - containerPort: 7001
          volumeMounts:
          - mountPath: %CREATE_DOMAIN_SCRIPT_DIR%
            name: create-fmw-infra-sample-domain-job-cm-volume
          - mountPath: %DOMAIN_ROOT_DIR%
            name: fmw-infra-sample-domain-storage-volume
          - mountPath: /weblogic-operator/secrets
            name: fmw-infra-credentials-volume
          - mountPath: /weblogic-operator/rcu-secrets
            name: rcu-credentials-volume
          command: ["/bin/sh"]
          args: ["%CREATE_DOMAIN_SCRIPT_DIR%/%CREATE_DOMAIN_SCRIPT%"]
          env:
            - name: DOMAIN_UID
              value: "%DOMAIN_UID%"
            - name: ADMIN_SERVER_NAME_SVC
              value: "%ADMIN_SERVER_NAME_SVC%"
            - name: T3_CHANNEL_PORT
              value: "%T3_CHANNEL_PORT%"
            - name: T3_PUBLIC_ADDRESS
              value: "%T3_PUBLIC_ADDRESS%"
            - name: MANAGED_SERVER_NAME_BASE_SVC
              value: "%MANAGED_SERVER_NAME_BASE_SVC%"
            - name: CREATE_DOMAIN_SCRIPT_DIR
              value: "%CREATE_DOMAIN_SCRIPT_DIR%"
            - name: DOMAIN_ROOT_DIR
              value: "%DOMAIN_ROOT_DIR%"
            - name: DOMAIN_HOME_DIR
              value: "%DOMAIN_HOME%"
            - name: DOMAIN_LOGS_DIR
              value: "%DOMAIN_ROOT_DIR%/logs/%DOMAIN_UID%"
            - name: CUSTOM_DOMAIN_NAME
              value: "%DOMAIN_NAME%"
            - name: CUSTOM_ADMIN_LISTEN_PORT
              value: "%ADMIN_PORT%"
            - name: CUSTOM_ADMIN_NAME
              value: "%ADMIN_SERVER_NAME%"
            - name: CUSTOM_ADMIN_HOST
              value: "%CUSTOM_ADMIN_HOST%"
            - name: CUSTOM_MANAGEDSERVER_PORT
              value: "%MANAGED_SERVER_PORT%"
            - name: CUSTOM_MANAGED_BASE_NAME
              value: "%MANAGED_SERVER_NAME_BASE%"
            - name: CUSTOM_MANAGED_SERVER_COUNT
              value: "%CONFIGURED_MANAGED_SERVER_COUNT%"
            - name: CUSTOM_CLUSTER_NAME
              value: "%CLUSTER_NAME%"
            - name: CUSTOM_RCUPREFIX
              value: "%CUSTOM_RCUPREFIX%"
            - name: CUSTOM_PRODUCTION_MODE
              value: "%PRODUCTION_MODE_ENABLED%"
            - name: CUSTOM_CONNECTION_STRING
              value: "%CUSTOM_CONNECTION_STRING%"
            - name: EXPOSE_T3_CHANNEL_PREFIX
              value: "%EXPOSE_T3_CHANNEL_PREFIX%"
      volumes:
        - name: create-fmw-infra-sample-domain-job-cm-volume
          configMap:
            name: %DOMAIN_UID%-create-fmw-infra-sample-domain-job-cm
        - name: fmw-infra-sample-domain-storage-volume
          persistentVolumeClaim:
            claimName: %DOMAIN_PVC_NAME%
        - name: fmw-infra-credentials-volume
          secret:
            secretName: %WEBLOGIC_CREDENTIALS_SECRET_NAME%
        - name: rcu-credentials-volume
          secret:
            secretName: %RCU_CREDENTIALS_SECRET_NAME%
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%imagePullSecrets:
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%- name: %WEBLOGIC_IMAGE_PULL_SECRET_NAME%
