# Copyright 2018 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
name: apache-webtier
version: 1.0.0
appVersion: 12.2.1.3
description: Chart for Apache HTTP Server
keywords:
- apache
- http
- https
- load balance
- proxy
home: https://httpd.apache.org
sources:
- https://github.com/oracle/weblogic-kubernetes-operator/tree/master/kubernetes/samples/charts/apache-webtier
maintainers:
- name: Oracle
engine: gotpl
