# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 
# Apache webtier docker image
image: "oracle/apache:12.2.1.3"

# imagePullPolicy specifies the image pull policy for the apache webiter docker image
imagePullPolicy: "IfNotPresent"

# imagePullSecrets contains an optional list of Kubernetes secrets, that are needed
# to access the registry containing the apache webtier image.
# If no secrets are required, then omit this property.
# 
# Example : a secret is needed, and has been stored in 'my-apache-webtier-secret'
#
# imagePullSecrets:
# - name: my-apache-webtier-secret
#
# imagePullSecrets:
# - name:

# Volume path for Apache webtier. By default, it is empty, which causes the volume
# mount be disabled and, therefore, the built-in Apache plugin config be used.
# Use this to provide your own Apache webtier configuration as needed; simply define this 
# path and put your own custom_mod_wl_apache.conf file under this path.
persistentVolumeClaimName:

# Boolean indicating if RBAC resources should be created
createRBAC: true

# NodePort to expose for http access
httpNodePort: 30305

# NodePort to expose for https access
httpsNodePort: 30443

# The VirtualHostName of the Apache HTTP server. It is used to enable custom SSL configuration.
# If it is set, the Apache HTTP Server is configured to listen to port 4433 for SSL traffic.
virtualHostName:

# The customer supplied certificate to use for Apache webtier SSL configuration.
# The value must be a string containing a base64 encoded certificate.
# If 'virtualHostName' is set, the custom certificate and private key are not provided,
# the default built-in auto-generated sample certificate and private key in the apache image will be used.
# This parameter is ignored if 'virtualHostName' is not set.
customCert:

# The customer supplied private key to use for Apache webtier SSL configuration.
# The value must be a string containing a base64 encoded key.
# If 'virtualHostName' is set, the custom certificate and private key are not provided,
# the default built-in auto-generated sample certificate and private key in the apache image will be used.
# This parameter is ignored if 'virtualHostName' is not set.
customKey:

# Unique ID identifying a domain.
# This ID must not contain an underscore ("_"), and must be lowercase and unique across all domains in a Kubernetes cluster.
domainUID: "domain1"

# Cluster name
clusterName: "cluster-1"

# Name of the admin server
adminServerName: "admin-server"

# Port number for admin server
adminPort: 7001

# Port number for each managed server
managedServerPort: 8001

# Prepath for all application deployed on WebLogic cluster.
# For example, if it is set to '/weblogic', all applications deployed on the cluster can be accessed via 
# http://myhost:myport/weblogic/application_end_url
# where 'myhost' is the IP of the machine that runs the Apache web tier, and 
#       'myport' is the port that the Apache web tier is publicly exposed to.
location: "/weblogic"

# Use non privileged port 8080 to listen. If set to false, default privileged port 80 will be used.
useNonPriviledgedPorts: false
