# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "VOYAGER" }}
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
spec:
  rules:
  - host: '*'
    http:
      nodePort: '{{ .Values.voyager.webPort }}'
      paths:
      - backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
          servicePort: '{{ .Values.wlsDomain.managedServerPort }}'

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager-stats
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 56789
      targetPort: 56789
      nodePort: {{ .Values.voyager.statsPort }}
  selector:
    origin: voyager
    origin-name: {{ .Values.wlsDomain.domainUID }}-voyager
{{- end }}
