domainInfo:
    AdminUserName: '@@FILE:/weblogic-operator/secrets/username@@'
    AdminPassword: '@@FILE:/weblogic-operator/secrets/password@@'
    ServerStartMode: prod
topology:
    AdminServerName: '@@PROP:adminServerName@@'
    Name: '@@PROP:domainName@@'
    ProductionModeEnabled: '@@PROP:productionModeEnabled@@'
    Cluster:
        '@@PROP:clusterName@@':
    Server:
        '@@PROP:adminServerName@@':
            ListenAddress: '@@PROP:domainUID@@-@@PROP:adminServerName@@'
            Log:
                FileName: '/shared/logs/@@PROP:adminServerName@@.log'
            NetworkAccessPoint:
                T3Channel:
                    ListenAddress: '@@PROP:domainUID@@-@@PROP:adminServerName@@'
                    ListenPort: '@@PROP:t3ChannelPort@@'
                    PublicAddress: '@@PROP:t3PublicAddress@@'
                    PublicPort: '@@PROP:t3ChannelPort@@'
        '@@PROP:managedServerNameBase@@1':
            Cluster: '@@PROP:clusterName@@'
            ListenAddress: '@@PROP:domainUID@@-@@PROP:managedServerNameBase@@1'
            ListenPort: '@@PROP:managedServerPort@@'
            NumOfRetriesBeforeMsiMode: 0
            RetryIntervalBeforeMsiMode: 1
            JTAMigratableTarget:
                Cluster: '@@PROP:clusterName@@'
                UserPreferredServer: '@@PROP:managedServerNameBase@@1'
            Log:
                FileName: '/shared/logs/@@PROP:managedServerNameBase@@1.log'
        '@@PROP:managedServerNameBase@@2':
            Cluster: '@@PROP:clusterName@@'
            ListenAddress: '@@PROP:domainUID@@-@@PROP:managedServerNameBase@@2'
            ListenPort: '@@PROP:managedServerPort@@'
            NumOfRetriesBeforeMsiMode: 0
            RetryIntervalBeforeMsiMode: 1
            JTAMigratableTarget:
                Cluster: '@@PROP:clusterName@@'
                UserPreferredServer: '@@PROP:managedServerNameBase@@2'
            Log:
                FileName: '/shared/logs/@@PROP:managedServerNameBase@@2.log'
        '@@PROP:managedServerNameBase@@3':
            Cluster: '@@PROP:clusterName@@'
            ListenAddress: '@@PROP:domainUID@@-@@PROP:managedServerNameBase@@3'
            ListenPort: '@@PROP:managedServerPort@@'
            NumOfRetriesBeforeMsiMode: 0
            RetryIntervalBeforeMsiMode: 1
            JTAMigratableTarget:
                Cluster: '@@PROP:clusterName@@'
                UserPreferredServer: '@@PROP:managedServerNameBase@@3'
            Log:
                FileName: '/shared/logs/@@PROP:managedServerNameBase@@3.log'
    MigratableTarget:
        '@@PROP:managedServerNameBase@@1 (migratable)':
            Cluster: '@@PROP:clusterName@@'
            UserPreferredServer: '@@PROP:managedServerNameBase@@1'
        '@@PROP:managedServerNameBase@@2 (migratable)':
            Cluster: '@@PROP:clusterName@@'
            UserPreferredServer: '@@PROP:managedServerNameBase@@2'
        '@@PROP:managedServerNameBase@@3 (migratable)':
            Cluster: '@@PROP:clusterName@@'
            UserPreferredServer: '@@PROP:managedServerNameBase@@3'

