# Copyright (c) 2019, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# This is an example of how to set up the Secret with the WebLogic Admin credentials.
# Please note that this method used encoded, but not encrypted data.
# We recommend that you use the command line alternative from a secure environment instead,
# i.e. kubectl create secret ...
apiVersion: v1
kind: Secret
metadata:
  # Note that this MUST match the name defined in the Domain Custom Resource
  name: %DOMAIN_UID%-weblogic-credentials
  namespace: %NAMESPACE%
  labels:
    weblogic.domainUID: %DOMAIN_UID%
    weblogic.domainName: %DOMAIN_NAME%
type: Opaque
data:
  # data is base64 encoded like this: `echo -n "weblogic" | base64`
  # In this example, username is weblogic, password is welcome1
  username: d2VibG9naWM=
  password: d2VsY29tZTE=
