apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rcu
  name: rcu
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.3
    imagePullPolicy: Always
    name: rcu
  imagePullSecrets:
           - name: docker-store
