# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Ref https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml
ports:
  web:
    nodePort: 30305
  websecure:
    nodePort: 30443

additionalArguments: 
  - "--log.level=INFO"
