# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: traefik-pathrouting-1
  namespace: weblogic-domain1
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/domain1`)
    middlewares:
    - name: middleware-domain1
      namespace: weblogic-domain1
    services:
    - kind: Service
      name: domain1-cluster-cluster-1
      port: 8001
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middleware-domain1
  namespace: weblogic-domain1
spec:
  replacePathRegex:
    regex: ^/domain1(.*)
    replacement: /testwebapp$1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: traefik-pathrouting-2
  namespace: weblogic-domain2
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/domain2`)
    middlewares:
    - name: middleware-domain2
      namespace: weblogic-domain2
    services:
    - kind: Service
      name: domain2-cluster-cluster-1
      port: 8001
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middleware-domain2
  namespace: weblogic-domain2
spec:
  replacePathRegex:
    regex: ^/domain2(.*)
    replacement: /testwebapp$1
