---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  namespace: %NAMESPACE%
  labels:
    weblogic.domainUID: %DOMAIN_UID%
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  namespace: %NAMESPACE%
  labels:
    app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
    weblogic.domainUID: %DOMAIN_UID%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  template:
    metadata:
      labels:
        app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
        weblogic.domainUID: %DOMAIN_UID%
    spec:
      serviceAccountName: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.4.5
        name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "30Mi"
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: dash
          containerPort: 8080
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  namespace: %NAMESPACE%
  labels:
    app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
    weblogic.domainUID: %DOMAIN_UID%
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
    [kubernetes]
    labelselector = "weblogic.domainUID=%DOMAIN_UID%,weblogic.clusterName=%CLUSTER_NAME%"
    [web]
    address = ":8080"
---
kind: Service
apiVersion: v1
metadata:
  name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  namespace: %NAMESPACE%
  labels:
    weblogic.domainUID: %DOMAIN_UID%
spec:
  selector:
    app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  ports:
  - port: 80
    name: http
    targetPort: http
    nodePort: %LOAD_BALANCER_WEB_PORT%
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik-dashboard
  namespace: %NAMESPACE%
  labels:
    app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
    weblogic.domainUID: %DOMAIN_UID%
spec:
  selector:
    app: %DOMAIN_UID%-%CLUSTER_NAME_LC%-traefik
  ports:
  - port: 8080
    name: dash
    targetPort: dash
    nodePort: %LOAD_BALANCER_ADMIN_PORT%
  type: NodePort
