# Copyright 2017, 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: %DOMAIN_UID%-weblogic-domain-pv
  labels:
    weblogic.domainUID: %DOMAIN_UID%
spec:
  storageClassName: %DOMAIN_UID%-weblogic-domain-storage-class
  capacity:
    storage: %WEBLOGIC_DOMAIN_STORAGE_SIZE%
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  %HOST_PATH_PREFIX%hostPath:
  %NFS_PREFIX%nfs:
    %NFS_PREFIX%server: %WEBLOGIC_DOMAIN_STORAGE_NFS_SERVER%
    path: "%WEBLOGIC_DOMAIN_STORAGE_PATH%"
