# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{ if .Values.customCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apache.fullname" . }}-cert
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  tls.crt: {{ .Values.customCert | quote }}
  tls.key: {{ .Values.customKey | quote }}
{{ end }}
