# Copyright 2018 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apache.fullname" . }}
    release: "{{ .Release.Name }}"
spec:
  type: NodePort
  selector:
    app: {{ template "apache.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - port: 80
      nodePort: {{ .Values.httpNodePort }}
      name: http
    - port: 443
      nodePort: {{ .Values.httpsNodePort }}
      name: https

