# Copyright 2018, 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    weblogic.resourceVersion: "loadbalancer-v2"
spec:
  type: NodePort
  selector:
    app: {{ template "apache.fullname" . }}
    weblogic.resourceVersion: "loadbalancer-v2"
  ports:
    - port: 80
      nodePort: {{ .Values.httpNodePort }}
      name: http
{{- if .Values.virtualHostName }}
    - port: 4433
{{- else }}
    - port: 443
{{- end }}
      nodePort: {{ .Values.httpsNodePort }}
      name: https

