# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: NodePort
  selector:
    app: {{ template "apache.fullname" . }}
  ports:
{{- if .Values.useNonPriviledgedPorts }}
    - port: 8080
{{- else}}
    - port: 80
{{- end }}
      nodePort: {{ .Values.httpNodePort }}
      name: http
{{- if .Values.virtualHostName }}
    - port: 4433
{{- else }}
    - port: 443
{{- end }}
      nodePort: {{ .Values.httpsNodePort }}
      name: https

