# Copyright 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

# Port number for admin server
adminPort: 7001

# Name of the Admin Server
adminServerName: admin-server

# Script used to create the domain.
createDomainScript: /u01/weblogic/create-domain-script.sh

# Name of the WebLogic domain to create
domainName: base_domain

# Unique id identifying a domain.
# This id must be lowercase and unique across all domains in a Kubernetes cluster
domainUid: domain1

# Type of WebLogic Cluster (static or dynamic)
clusterType: dynamic

# Cluster name
clusterName: cluster-1

# Number of managed servers to generate for the domain
managedServerCount: 2

# Number of managed servers to initially start for the domain
managedServerStartCount: 1

# Maximum number of managed server instances allowed to be created
maxManagedServerCount: 8

# Base string used to generate managed server names
managedServerNameBase: managed-server

# Port number for each managed server
managedServerPort: 8001

# Physical path of the persistent volume storage
persistencePath: /scratch/k8s_dir/persistentVolume001

# Total storage allocated by the persistent volume
persistenceSize: 10Gi

# Name of the storage class to set for the persistent volume and persistent volume claim
# The default value that will be used is the value of the domainUid input parameter
# The name of the storage class must be in lowercase
#persistenceStorageClass:

# Name of the Kubernetes persistent volume claim for this domain.  Name must be lowercase.
# The persistent volume claim name will be prepended with '${domainUid}-' by create-domain-job.sh
# if it is not already
persistenceVolumeClaimName: pv001-claim

# Name of the Kubernetes persistent volume for this domain.  Name must be lowercase.
# The persistent volume name will be prepended with '${domainUid}-' by create-domain-job.sh
# if it is not already
persistenceVolumeName: pv001

# Boolean indicating if production mode is enabled for the domain
productionModeEnabled: true

# Name of the Kubernetes secret for the Admin Server's username and password
# The name must be lowercase
secretName: domain1-weblogic-credentials

# Name of the Kubernetes secret to access the Docker Store to pull the WebLogic Server Docker image
# The presence of the secret will be validated when this parameter is enabled.
#imagePullSecretName:

# Port for the T3Channel of the NetworkAccessPoint
t3ChannelPort: 30012

# Public address for T3Channel of the NetworkAccessPoint.  This value should be set to the
# kubernetes server address, which you can get by running "kubectl cluster-info".  If this
# value is not set to that address, WLST will not be able to connect from outside the
# kubernetes cluster.
t3PublicAddress: kubernetes

# Boolean to indicate if the channel should be exposed as a service
exposeAdminT3Channel: false

# NodePort to expose for the admin server
adminNodePort: 30701

# Boolean to indicate if the adminNodePort will be exposed
exposeAdminNodePort: false

# Name of the domain namespace
namespace: default

# Load balancer to deploy.  Supported values are: traefik, none
loadBalancer: traefik

# Load balancer web port
loadBalancerWebPort: 30305

# Load balancer admin port
loadBalancerAdminPort: 30315

#Java Option for Weblogic Server
javaOptions: -Dweblogic.StdoutDebugEnabled=false
