# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ConfigMap
metadata:
  name: %DOMAIN_UID%-delete-weblogic-sample-domain-job-cm
  namespace: %NAMESPACE%
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: %DOMAIN_UID%
    weblogic.domainName: %DOMAIN_NAME%
data:
  delete-domain-job.sh: |-
      #!/bin/bash
      #
      # delete domainHome folder
      rm -rf ${DOMAIN_HOME_DIR}

      echo "Delete Completed"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: %DOMAIN_UID%-delete-weblogic-sample-domain-job
  namespace: %NAMESPACE%
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        weblogic.resourceVersion: domain-v2
        weblogic.domainUID: %DOMAIN_UID%
        weblogic.domainName: %DOMAIN_NAME%
        app: %DOMAIN_UID%-delete-weblogic-sample-domain-job
    spec:
      restartPolicy: Never
      containers:
        - name: delete-weblogic-sample-domain-job
          image: %WEBLOGIC_IMAGE%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          volumeMounts:
          - mountPath: /u01/weblogic
            name: delete-weblogic-sample-domain-job-cm-volume
          - mountPath: %DOMAIN_ROOT_DIR%
            name: weblogic-sample-domain-storage-volume
          command: ["/bin/sh"]
          args: ["/u01/weblogic/delete-domain-job.sh"]
          env:
            - name: DOMAIN_HOME_DIR
              value: %DOMAIN_HOME%
            - name: DOMAIN_LOGS_DIR
              value: %DOMAIN_ROOT_DIR%/logs/%DOMAIN_UID%
      volumes:
        - name: delete-weblogic-sample-domain-job-cm-volume
          configMap:
            name: %DOMAIN_UID%-delete-weblogic-sample-domain-job-cm
        - name: weblogic-sample-domain-storage-volume
          persistentVolumeClaim:
            claimName: %DOMAIN_PVC_NAME%
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%imagePullSecrets:
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%- name: %WEBLOGIC_IMAGE_PULL_SECRET_NAME%
