# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: "weblogic.oracle/v2"
kind: Domain
metadata:
  name: domain1-uid
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1-uid
spec:
  image: domain1:{{ .Values.Version }}
  imagePullPolicy: "Never"
  webLogicCredentialsSecret: 
    name: domain1-uid-weblogic-credentials
  includeServerOutInPodLog: true
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
  adminServer:
    adminService:
      channels:
      - channelName: default
        nodePort: 30701
      - channelName: T3Channel
  replicas: 3
