# Copyright 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

name: weblogic-domain
version: 2.0
description: Helm package for creation of WebLogic domain.
