# Copyright (c) 2021, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# Description
#  Use Hugo to build static site and publish to gh-pages
#
name: "PublishGitHubPages"

on:
  push:
    branches:
      - release/4.0
    paths:
      - 'documentation/**'
  schedule:
    - cron: '15 3 * * *'

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 32
          path: branch

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.PUBLISH_SECRET }}

      - name: Build and publish site
        run: |
          curl -fL -o hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v0.108.0/hugo_0.108.0_Linux-64bit.tar.gz"
          tar -xf hugo.tar.gz
          export PATH="$PWD:$PATH"
          mkdir $GITHUB_WORKSPACE/WORK
          cd $GITHUB_WORKSPACE/branch/documentation
          echo "Documentation branch is $GITHUB_REF_NAME..."
          echo "Building documentation for latest minor version..."
          hugo -s site -d "$GITHUB_WORKSPACE/WORK" -b https://oracle.github.io/weblogic-kubernetes-operator
          echo "Copying static files into place..."
          cp -R charts domains "$GITHUB_WORKSPACE/WORK"
          cd $GITHUB_WORKSPACE/gh-pages
          find . -maxdepth 1 -mindepth 1 -not -name '[0-9]*' -exec rm -Rf {} \;
          cp -R $GITHUB_WORKSPACE/WORK/* .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Documentation update from publish GitHub Action"
          git push origin gh-pages