# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: %PERSISTENT_VOLUME_NAME%
  labels:
    usage: %PERSISTENT_VOLUME_NAME%
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: %STORAGE_CLASS_NAME%
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: %AZURE_FILE_SHARE_SECRET_NAME%
    shareName: %AZURE_FILE_SHARE_NAME%
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
